# Generated by Django 5.1 on 2024-10-16 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='collections/%Y/%m/', verbose_name='Фото коллекции')),
                ('name', models.CharField(default=None, max_length=50, unique=True, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='ItemInCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothcollections.collection')),
                ('item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.clothitem', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в Коллекции',
                'verbose_name_plural': 'Товары в Коллекции',
            },
        ),
    ]
